# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd114a7a6f35ab43107a9c428d0ccdc6"
application_url = "https://example.com"
embedded = true
name = "discount-spinner-app"

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://example.com"
subpath = "discount-spinner-proxy"
prefix = "apps"
