# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd114a7a6f35ab43107a9c428d0ccdc6"
name = "discount-spinner-app"
application_url = "https://discount-spinner-pink.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [ "https://discount-spinner-pink.vercel.app/auth/callback" ]

[app_proxy]
url = "https://discount-spinner-pink.vercel.app"
subpath = "discount-spinner-proxy"
prefix = "apps"
